rmin: 0.1
rmax: 100
nneighbours: 8
nsamples: 1.e+7
batch_size: 1.e+6
neval: 10000
seed: 42
nbins_marks: 10


################################################################################
#                                 totpartmass                                 #
################################################################################


"mass001":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 12.4
    islog: true

"mass002":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 12.6
    islog: true

"mass003":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 12.8
    islog: true

"mass004":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 13.0
    islog: true

"mass005":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 13.2
    islog: true

"mass006":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 13.4
    islog: true

"mass007":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 13.6
    islog: true

"mass008":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 13.8
    islog: true

"mass009":
  primary:
    name:
    - totpartmass
    - group_mass
    min: 14.0
    islog: true